# Generated by Django 3.2.25 on 2026-04-18 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.TimeField(default=datetime.time(8, 0), verbose_name='Horario de apertura')),
                ('close_time', models.TimeField(default=datetime.time(21, 0), verbose_name='Horario de cierre')),
                ('interval_minutes', models.IntegerField(default=30, verbose_name='Intervalo (min)')),
            ],
            options={
                'verbose_name': 'Configuración de Turnos',
                'verbose_name_plural': 'Configuraciones de Turnos',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('client_last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('completed', 'Completado'), ('absent', 'Ausente')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['date', 'time'],
                'unique_together': {('date', 'time')},
            },
        ),
    ]
