# Generated by Django 3.2.25 on 2026-04-18 04:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token único'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='cancellation_limit_hours',
            field=models.IntegerField(default=24, verbose_name='Límite de Cancelación (horas)'),
        ),
    ]
